# Generated by Django 2.1.10 on 2019-11-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', upload_to='images/%Y/%m')),
            ],
        ),
    ]
