# Generated by Django 2.1.10 on 2019-11-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updateheadpoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('avatar', models.FileField(default='headimages/default.png', upload_to='headimages/%Y/%m/%d/', verbose_name='头像')),
            ],
        ),
    ]
