# Generated by Django 2.1.10 on 2019-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0002_updateheadpoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='Temp',
            field=models.CharField(max_length=16, verbose_name='作者'),
        ),
    ]
