# Generated by Django 2.1.10 on 2019-12-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0003_auto_20191202_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateheadpoto',
            options={'verbose_name': '更换头像', 'verbose_name_plural': '更换头像'},
        ),
    ]
