# Generated by Django 2.1.10 on 2019-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0004_auto_20191204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='推荐言行'),
        ),
    ]
