# Generated by Django 2.1.10 on 2019-12-31 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0005_auto_20191205_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
