# Generated by Django 2.1.10 on 2020-01-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnchat', '0006_auto_20191231_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='headphoto',
            field=models.FileField(default='headimages/default.png', upload_to='headimages/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
