# Generated by Django 2.1.10 on 2019-11-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='评论内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('chats_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='评论作者')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
                'ordering': ('pub_date',),
            },
        ),
    ]
