# Generated by Django 2.1.10 on 2019-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191205_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
