# Generated by Django 2.1.10 on 2019-12-31 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户简介', 'verbose_name_plural': '用户简介'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(max_length=50, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='用户名'),
        ),
    ]
