# Generated by Django 2.1.10 on 2020-01-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191231_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-time_now'], 'verbose_name': '注册用户', 'verbose_name_plural': '注册用户'},
        ),
    ]
