# Generated by Django 2.1.10 on 2019-12-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findnearhistory',
            name='photo',
            field=models.FileField(default='headimages/history.png', upload_to='headimages/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='findnearhistory',
            name='history',
            field=models.TextField(null=True, verbose_name='历史'),
        ),
    ]
