# Generated by Django 2.1.10 on 2019-12-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findhistory', '0002_auto_20191206_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findnearhistory',
            options={'ordering': ['-timenow'], 'verbose_name': '挖掘历史', 'verbose_name_plural': '挖掘历史'},
        ),
    ]
